name: mf6adj
channels:
  - conda-forge
  - nodefaults
dependencies:
  - scipy
  - numpy>=2.0
  - matplotlib
  - pandas>2.0
  - jupyter
  - notebook
  - jupyterlab
  - pytest
  - pytest-cov
  - pytest-xdist
  - nbmake
  - shapely
  - h5py
  - flopy
  - modflowapi
  - modflow6
  - pyemu
  - pyshp
  - ruff
  - codespell
  - pip
  - pip:
    - git+https://github.com/pypest/pyemu@develop
