name: mf6adj
channels:
  - conda-forge
  - defaults
dependencies:
  - scipy
  - numpy<2.0
  - matplotlib
  - pandas
  - jupyter
  - notebook
  - pytest
  - pytest-cov
  - pytest-xdist
  - nbmake
  - shapely
  - h5py
  - pip
  - pip:
    - git+https://github.com/pypest/pyemu@develop
    - pyshp
