name: mf6adj
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - matplotlib
  - pandas
  - jupyter
  - notebook
  - pytest
  - pytest-cov
  - pytest-xdist
  - nbmake
  - pip
  - pip:
    - git+https://github.com/pypest/pyemu@develop
